import jsPDF from 'jspdf'

const ReportSummary = ({ report }) => {
  const dateLabel = report?.PublishedDate
    ? new Date(report.PublishedDate).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })
    : 'No report yet'

  // Split summary into paragraphs on newlines
  const paragraphs = (report?.summary || '').split(/\n+/).filter(p => p.trim())

  const handleDownload = () => {
    const doc = new jsPDF({ unit: 'pt', format: 'a4' })

    const pageWidth = doc.internal.pageSize.getWidth()
    const pageHeight = doc.internal.pageSize.getHeight()
    const margin = 50
    const contentWidth = pageWidth - margin * 2
    const lineHeight = 16
    const paragraphGap = 12

    // Header bar
    doc.setFillColor(136, 59, 188)
    doc.rect(0, 0, pageWidth, 70, 'F')

    // Title
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(26)
    doc.setTextColor(255, 255, 255)
    doc.text('Weekly Report', margin, 45)

    // Date in header
    doc.setFontSize(11)
    doc.setFont('helvetica', 'normal')
    doc.text(dateLabel, pageWidth - margin, 45, { align: 'right' })

    // Section label
    doc.setTextColor(136, 59, 188)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(13)
    doc.text('Summary', margin, 110)

    // Divider
    doc.setDrawColor(136, 59, 188)
    doc.setLineWidth(1)
    doc.line(margin, 116, pageWidth - margin, 116)

    // Paragraphs with spacing
    doc.setTextColor(40, 40, 40)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(11)

    let y = 136
    const source = paragraphs.length > 0 ? paragraphs : ['No summary available.']

    source.forEach((para) => {
      const lines = doc.splitTextToSize(para.trim(), contentWidth)
      lines.forEach((line) => {
        if (y > pageHeight - 60) {
          doc.addPage()
          y = margin
        }
        doc.text(line, margin, y)
        y += lineHeight
      })
      y += paragraphGap
    })

    // Footer
    doc.setFontSize(9)
    doc.setTextColor(160, 160, 160)
    doc.text('Generated by Interior Design Portal', margin, pageHeight - 30)

    const filename = `report-${dateLabel.replace(/\s/g, '-')}.pdf`
    doc.save(filename)
  }

  return (
    <div className='w-full overflow-hidden rounded-lg bg-gradient-to-l from-[#f7d6f3] to-transparent px-2 py-3'>
      <div className="date-title w-full">
        <div className="date flex items-center mt-[2%] w-full gap-4">
          <div className="icon w-10 h-10 md:w-12 md:h-12 rounded-full bg-[#883bbc] items-center justify-center flex shrink-0">
            <i className="ri-file-chart-fill text-2xl text-white opacity-90"></i>
          </div>
          <div className="date text-xl leading-5 font-bold">
            <h4>{dateLabel}</h4>
          </div>
        </div>
      </div>

      {/* Rendered summary with paragraph spacing */}
      <div className="summary mt-[3%] font-semibold opacity-80 space-y-3">
        {paragraphs.length > 0
          ? paragraphs.map((para, i) => <p key={i}>{para}</p>)
          : <p>No weekly report has been generated yet.</p>
        }
      </div>

      <div className='full-summary w-full mt-[6%]'>
        <button
          onClick={handleDownload}
          className='w-full flex items-center justify-center gap-2 px-4 py-2 bg-[#883bbc] text-white rounded-md font-semibold text-base hover:bg-[#7a33ab] transition-colors'
        >
          <i className="ri-download-2-line text-xl"></i>
          <span>Download PDF</span>
        </button>
      </div>
    </div>
  )
}

export default ReportSummary
